# Generated by Django 5.0.1 on 2025-10-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('task_type', models.CharField(choices=[('once', '한 번만'), ('daily', '매일'), ('weekly', '요일별'), ('period', '기간')], default='once', max_length=10, verbose_name='할 일 타입')),
                ('priority', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('active', '활성'), ('archived', '보관')], default='active', max_length=10, verbose_name='상태')),
                ('repeat_days', models.CharField(blank=True, help_text='Mon,Tue,Wed,Thu,Fri,Sat,Sun 형식', max_length=50, verbose_name='반복 요일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='보관일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '할 일',
                'verbose_name_plural': '할 일 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
