# Generated by Django 5.0.1 on 2025-10-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(verbose_name='완료 날짜')),
                ('completed_time', models.TimeField(auto_now_add=True, verbose_name='완료 시각')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task', verbose_name='할 일')),
            ],
            options={
                'verbose_name': '완료 기록',
                'verbose_name_plural': '완료 기록 목록',
                'ordering': ['-completed_date', '-completed_time'],
                'unique_together': {('task', 'completed_date')},
            },
        ),
    ]
